# Generated by Django 5.2 on 2025-04-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varaitions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varaitions',
            new_name='variations',
        ),
    ]
